### ISSUE TITLE
!kaamelott aller chercher un son random sur <http://kaamelott-soundboard.2ec0b4.fr>

### ISSUE THREAD

**Issue by logscl** [logscl/nicobot-slack#117]
- Requested by roux

**Comment by jlamby** [comment]
La liste des sons dans la soundboard : 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mi_ours_mi_scorpion 
- http://kaamelott-soundboard.2ec0b4.fr/#son/2_3_poils_de_Q 
- http://kaamelott-soundboard.2ec0b4.fr/#son/a_kadoc 
- http://kaamelott-soundboard.2ec0b4.fr/#son/a_la_volette1 
- http://kaamelott-soundboard.2ec0b4.fr/#son/a_moi_a_lassassin 
- http://kaamelott-soundboard.2ec0b4.fr/#son/un_bon_quart_dheure 
- http://kaamelott-soundboard.2ec0b4.fr/#son/a_plus_tard 
- http://kaamelott-soundboard.2ec0b4.fr/#son/a_roulettes 
- http://kaamelott-soundboard.2ec0b4.fr/#son/apres_pour_le_detail_je_sais_pas 
- http://kaamelott-soundboard.2ec0b4.fr/#son/faut_ce_qui_faut 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ah_cest_ca 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_pas_jo_le_rigolo 
- http://kaamelott-soundboard.2ec0b4.fr/#son/a_voui_vous_avez_raison 
- http://kaamelott-soundboard.2ec0b4.fr/#son/commencez_pas_a_me_faire_chier 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ah_le_printemps_on_crame_des_mecs 
- http://kaamelott-soundboard.2ec0b4.fr/#son/alors_ca_vient_ptite_bite 
- http://kaamelott-soundboard.2ec0b4.fr/#son/arthour 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_la_crachez_votre_pastille 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bien_manger_cest_important 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bon_ben_revolte 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bon_cassez_vous 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_bien_fait 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pas_de_quoi_en_chier_une_galette 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_de_la_merde 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_ya_rien_a_developper_cest_de_la_merde_cest_tout 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_debile_cette_histoire 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_honteux 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_le_rendez_vous_des_glandus_la_ou_quoi 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_pas_faux1 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_que_cest_pas_une_blague 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_plus_filiforme 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_vrai_quelle_reste 
- http://kaamelott-soundboard.2ec0b4.fr/#son/un_genre_cake 
- http://kaamelott-soundboard.2ec0b4.fr/#son/jpeux_pas_vous_dire 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ca_va_encore_faire_des_discussions_a_rallonge 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ca_vous_ennuie_si_je_vomis 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ca_vous_fait_pas_mal_a_la_tete_de_glandouiller 
- http://kaamelott-soundboard.2ec0b4.fr/#son/charmant 
- http://kaamelott-soundboard.2ec0b4.fr/#son/chui_un_marteau_moi 
- http://kaamelott-soundboard.2ec0b4.fr/#son/comment 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cuillere 
- http://kaamelott-soundboard.2ec0b4.fr/#son/des_vetements 
- http://kaamelott-soundboard.2ec0b4.fr/#son/dites_tirez_vous 
- http://kaamelott-soundboard.2ec0b4.fr/#son/il_est_pas_beau_mon_graal 
- http://kaamelott-soundboard.2ec0b4.fr/#son/elle_est_ou_la_poulette 
- http://kaamelott-soundboard.2ec0b4.fr/#son/en_garde_ma_mignone 
- http://kaamelott-soundboard.2ec0b4.fr/#son/en_garde_espece_de_vieille_pute_degarnie 
- http://kaamelott-soundboard.2ec0b4.fr/#son/est_ce_que_peut_servir_elan_pigeon 
- http://kaamelott-soundboard.2ec0b4.fr/#son/est-ce_que_vous_pouvez_vous_barrer_maintenant 
- http://kaamelott-soundboard.2ec0b4.fr/#son/et_alors_faut_un_permis 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bataille_de_fions 
- http://kaamelott-soundboard.2ec0b4.fr/#son/et_puis_quoi_encore 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_moi_ou_il_y_a_une_ambiance_de_merde 
- http://kaamelott-soundboard.2ec0b4.fr/#son/evidemment_quelquun 
- http://kaamelott-soundboard.2ec0b4.fr/#son/venir_foutre_votre_merde 
- http://kaamelott-soundboard.2ec0b4.fr/#son/fort_en_pomme_2 
- http://kaamelott-soundboard.2ec0b4.fr/#son/fort_en_pomme_1 
- http://kaamelott-soundboard.2ec0b4.fr/#son/he_les_connards_vous_pouvez_faire_griller_un_porcelet 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bucher1 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bucher2 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bucher3 
- http://kaamelott-soundboard.2ec0b4.fr/#son/honnetement_je_connais_pas_le_mot_la 
- http://kaamelott-soundboard.2ec0b4.fr/#son/il_pue_il_pete 
- http://kaamelott-soundboard.2ec0b4.fr/#son/il_ressemble_a_tatan 
- http://kaamelott-soundboard.2ec0b4.fr/#son/burgonde_ou_anglais 
- http://kaamelott-soundboard.2ec0b4.fr/#son/interprete 
- http://kaamelott-soundboard.2ec0b4.fr/#son/insipide 
- http://kaamelott-soundboard.2ec0b4.fr/#son/j_ai_le_droit_d_etre_4_jours_pas_chez_moi 
- http://kaamelott-soundboard.2ec0b4.fr/#son/jai_pas_envie_de_voir_vos_tronches 
- http://kaamelott-soundboard.2ec0b4.fr/#son/jai_toujours_ete_fascine_par_le_monde_paysan 
- http://kaamelott-soundboard.2ec0b4.fr/#son/rien_a_carer 
- http://kaamelott-soundboard.2ec0b4.fr/#son/deux_trous_du_cul_soient_plus_efficaces_qu_un_seul 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_pas_une_sinecure 
- http://kaamelott-soundboard.2ec0b4.fr/#son/je_vais_vous_passer_le_gout_du_plein_air_moi 
- http://kaamelott-soundboard.2ec0b4.fr/#son/je_vois_pas_le_rapport_avec_bretagne 
- http://kaamelott-soundboard.2ec0b4.fr/#son/jvoudrais_pas_faire_ma_raclette 
- http://kaamelott-soundboard.2ec0b4.fr/#son/la_gerbe 
- http://kaamelott-soundboard.2ec0b4.fr/#son/soupcon_gros_nul 
- http://kaamelott-soundboard.2ec0b4.fr/#son/je_pourrais_gueuler_dans_le_cul_dun_poney 
- http://kaamelott-soundboard.2ec0b4.fr/#son/fulgurant 
- http://kaamelott-soundboard.2ec0b4.fr/#son/je_ne_mange_pas_de_graines 
- http://kaamelott-soundboard.2ec0b4.fr/#son/je_refuse_daller_me_battre 
- http://kaamelott-soundboard.2ec0b4.fr/#son/epique 
- http://kaamelott-soundboard.2ec0b4.fr/#son/lair_idiote 
- http://kaamelott-soundboard.2ec0b4.fr/#son/je_vois_trouble 
- http://kaamelott-soundboard.2ec0b4.fr/#son/intro_comaque 
- http://kaamelott-soundboard.2ec0b4.fr/#son/la_bouffe_est_interdite 
- http://kaamelott-soundboard.2ec0b4.fr/#son/la_dedans_carbure 
- http://kaamelott-soundboard.2ec0b4.fr/#son/le_caca_des_pigeons_c_est_caca_faut_pas_manger 
- http://kaamelott-soundboard.2ec0b4.fr/#son/le_graal_par_ci_le_graal_par_la 
- http://kaamelott-soundboard.2ec0b4.fr/#son/le_gras_cest_la_vie 
- http://kaamelott-soundboard.2ec0b4.fr/#son/le_pognon_ca_va_ca_vient 
- http://kaamelott-soundboard.2ec0b4.fr/#son/le_poisson_le_petit_poisson 
- http://kaamelott-soundboard.2ec0b4.fr/#son/le_prochain_qui_l_ouvre_galeres_trois_ans 
- http://kaamelott-soundboard.2ec0b4.fr/#son/les_pattes_de_canard 
- http://kaamelott-soundboard.2ec0b4.fr/#son/madresse_pas_la_parole 
- http://kaamelott-soundboard.2ec0b4.fr/#son/quand_meme_raide 
- http://kaamelott-soundboard.2ec0b4.fr/#son/fournis_notice 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_allez_chier_dans_une_fiolle 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_arretez_de_discutailler_cinq_minutes 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_c_est_pas_possible_d_entendre_ca 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_faut_pas_deconner_ils_y_sont_pour_rien 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_je_vous_ai_dis_que_c_etait_important 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_je_vous_emmerde_mon_ptit_pote 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ma_femme_a_pas_de_moustache 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_qu_est_ce_que_j_en_ai_a_foutre 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mais_tout_a_fait 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_etes_completement_con 
- http://kaamelott-soundboard.2ec0b4.fr/#son/il_trouverait_meme_pas_sa_bite_pour_pisser 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mecreant 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mecreant_2 
- http://kaamelott-soundboard.2ec0b4.fr/#son/moi_jai_toujours_dit 
- http://kaamelott-soundboard.2ec0b4.fr/#son/moi_jai_toujours_dit2 
- http://kaamelott-soundboard.2ec0b4.fr/#son/moi_je_serais_vous_je_vous_ecouterais 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pique_diagonale 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mon_frere_y_peut_pas_aller_a_l_ecole 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mordu 
- http://kaamelott-soundboard.2ec0b4.fr/#son/laissez_le_a_lair 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vraiment_impressionnant 
- http://kaamelott-soundboard.2ec0b4.fr/#son/restez_pas_plante_la_comme_un_cepe 
- http://kaamelott-soundboard.2ec0b4.fr/#son/allez_boire_un_coup 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_admettrez_que_vous_etes_hors_normes 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_voulez_que_je_vous_degage_la_nuque_a_la_serpette 
- http://kaamelott-soundboard.2ec0b4.fr/#son/jvous_fait_confiance 
- http://kaamelott-soundboard.2ec0b4.fr/#son/sans_deconner 
- http://kaamelott-soundboard.2ec0b4.fr/#son/arretez_de_parler_aux_gens 
- http://kaamelott-soundboard.2ec0b4.fr/#son/nuo_pusso_volo 
- http://kaamelott-soundboard.2ec0b4.fr/#son/oh_cest_la_vacherie_ca 
- http://kaamelott-soundboard.2ec0b4.fr/#son/oh_la_vache 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ecartez-vous 
- http://kaamelott-soundboard.2ec0b4.fr/#son/politique_de_l_autruche 
- http://kaamelott-soundboard.2ec0b4.fr/#son/on_en_a_gros 
- http://kaamelott-soundboard.2ec0b4.fr/#son/on_est_forts 
- http://kaamelott-soundboard.2ec0b4.fr/#son/mettre_du_beurre_au_fond_du_plat 
- http://kaamelott-soundboard.2ec0b4.fr/#son/cest_pas_faux2 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ca_va_un_peu_trop_vite_pour_moi 
- http://kaamelott-soundboard.2ec0b4.fr/#son/stand_de_crepes 
- http://kaamelott-soundboard.2ec0b4.fr/#son/enquille 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ptite_pucelle 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pas_du_tout_les_lapins_les_lapins_c_est_gentil 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pays_de_galles_independant 
- http://kaamelott-soundboard.2ec0b4.fr/#son/plait_il 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pour_savoir_si_il_va_y_avoir_du_vent 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pourquoi_pas2 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pourquoi_pas1 
- http://kaamelott-soundboard.2ec0b4.fr/#son/pourquoi_qu_on_gueule 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ptetre_une_connerie 
- http://kaamelott-soundboard.2ec0b4.fr/#son/putain_il_est_fort_ce_con 
- http://kaamelott-soundboard.2ec0b4.fr/#son/qu-est_ce_dire_que_ceci 
- http://kaamelott-soundboard.2ec0b4.fr/#son/sourire_comme_des_glands 
- http://kaamelott-soundboard.2ec0b4.fr/#son/quand_on_gueule_sans_savoir_pourquoi 
- http://kaamelott-soundboard.2ec0b4.fr/#son/quand_on_se_fache 
- http://kaamelott-soundboard.2ec0b4.fr/#son/federer_mes_couilles 
- http://kaamelott-soundboard.2ec0b4.fr/#son/ca_change_tout 
- http://kaamelott-soundboard.2ec0b4.fr/#son/si_vous_etes_vendeur 
- http://kaamelott-soundboard.2ec0b4.fr/#son/toujours_se_plaindre_pequenauds 
- http://kaamelott-soundboard.2ec0b4.fr/#son/sortez-vous_les_doigts_du_cul 
- http://kaamelott-soundboard.2ec0b4.fr/#son/bonjour_la_pedagogie 
- http://kaamelott-soundboard.2ec0b4.fr/#son/tatan_elle_fait_des_flans 
- http://kaamelott-soundboard.2ec0b4.fr/#son/tu_la_fermes_definitivement 
- http://kaamelott-soundboard.2ec0b4.fr/#son/crame_ta_famille 
- http://kaamelott-soundboard.2ec0b4.fr/#son/petite_corne 
- http://kaamelott-soundboard.2ec0b4.fr/#son/voila_cest_pro 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_allez_fermer_vos_mouilles_oui 
- http://kaamelott-soundboard.2ec0b4.fr/#son/avez_de_la_chance 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_deconnez 
- http://kaamelott-soundboard.2ec0b4.fr/#son/la_monstruosite 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_nous_utilisez_bon_gre_mal_gre_pour_arriver_sur_la_fin 
- http://kaamelott-soundboard.2ec0b4.fr/#son/vous_rigolez_jespere 
- http://kaamelott-soundboard.2ec0b4.fr/#son/wooouuuhouhouhou_c_est_mortel 
- http://kaamelott-soundboard.2ec0b4.fr/#son/zut_la
