### ISSUE TITLE
!old &lt;link&gt; = recherche de la date de la premiere apparition du link sur les internet, gl hf

### ISSUE THREAD

**Issue by logscl** [logscl/nicobot-slack#32]
- Requested by neneb

**Comment by logscl** [comment]
nan !

**Comment by jlamby** [comment]
On pourrait avoir la date la 1ere parution du lien sur le chan avec https://github.com/jlamby/nicobot-persistence#service-links

Mais je ne sais plus si le requeteur est deja fait ds nicobot ou pas :D
