### ISSUE TITLE
[Feature request] Système de distribution de gomettes

### ISSUE THREAD

**Issue by B3nZ3n** [logscl/nicobot-slack#6]
Permettre à nicobot de lancer un vote (à la demande) pour l’attribution d'une gomette (verte ou rouge).
L'attribution de la gomette doit etre votée par X%des personnes connectées.
Si le vote succeed (minimum de votes requis dans un temps imparti (eg: 5mins)), +1 gomette.

Possible d'afficher les scores des utilisateurs à la demande et / ou a la fin du vote.

[easter egg]: le bot pourrait, nier le vote et décider seul / ne pas tenir compte du vote de certaines personnes... avec une probabilité faible.

**Comment by Chaf0uin** [comment]
Le bot pourrait systématiquement donner des gomettes rouges à Mika, puisqu'il, comme chacun le sait, ne l'aime pas.

**Comment by logscl** [comment]
Pour pas oublier :

>nicobotBOT 15:35
VOTE!! Gomette rouge pour letag? (Réponses: vote < oui | non > )
b3nz3n 15:35
vote oui
letag 15:35
vote non
batto 15:35
vote non
chaf 15:36
vote oui
nicobotBOT 15:36 VOTE TERMINE! Gomette rouge pour letag, because fuck you Im the boss.

**Comment by logscl** [comment]
100ab6678c5f5620efcd3332dfaf07135ccdfa5f
